spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: shop_goods_route
          #映射路径
#          uri: http://localhost:18081
          #映射到goods微服务名称并开启负载均衡（集群环境）
          uri: lb://goods
          predicates:
          #域名请求重定向
#          - Host=cloud.luohaiming.com**
          #路径请求重定向
#          - Path=/api/brand/**
          - Path=/**
          filters:
          #去掉请求路径中的第一个路径(api)
#          - StripPrefix=1
          #每个请求前面都加上/brand这个前缀
#          - PrefixPath=/brand
          - name: RequestRateLimiter
            args:
              #用户身份唯一识别标识符
              key-resolver: "#{@ipKeyResolver}"
              #每个IP每秒最大请求量
              redis-rate-limited.replenishRate: 1
              #允许由1个请求并发【宽限】
              redis-rate-limited.burstCapacity: 1
        - id: shop_user_route
          uri: lb://user
          predicates:
          - Path=/address/**,/area/**,/cities/**,/provinces/**,/user/**
          filters:
          - StripPrefix=1
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
  web:
    exposure:
      include: true